version: '3.3'

services:
   db:
     image: mysql:8.0
     cap_add:
       - SYS_NICE   
     ports:
       - "3306:3306"
     volumes:
       - ./db_data/db:/var/lib/mysql:rw
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: 123456

   wordpress:
     depends_on:
       - db
     image: wordpress:5.6
     volumes:
       - ./wordpress_data_test:/var/www/html:rw
     ports:
       - "88:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: 123456
       WORDPRESS_DB_NAME: wordpress
